// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/poker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateHandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly 2 hole cards for the player.
	HoleCards []string `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"` // e.g. ["HA", "S7"]
	// Exactly 5 community cards.
	CommunityCards []string `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"` // e.g. ["CT", "DQ", "HK", "S2", "C3"]
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateHandRequest) Reset() {
	*x = EvaluateHandRequest{}
	mi := &file_proto_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandRequest) ProtoMessage() {}

func (x *EvaluateHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandRequest.ProtoReflect.Descriptor instead.
func (*EvaluateHandRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateHandRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *EvaluateHandRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

type EvaluateHandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The best 5-card hand picked from hole + community.
	BestHand      []string `protobuf:"bytes,1,rep,name=best_hand,json=bestHand,proto3" json:"best_hand,omitempty"` // 5 card strings
	HandName      string   `protobuf:"bytes,2,opt,name=hand_name,json=handName,proto3" json:"hand_name,omitempty"` // e.g. "Three of a Kind"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateHandResponse) Reset() {
	*x = EvaluateHandResponse{}
	mi := &file_proto_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateHandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateHandResponse) ProtoMessage() {}

func (x *EvaluateHandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateHandResponse.ProtoReflect.Descriptor instead.
func (*EvaluateHandResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateHandResponse) GetBestHand() []string {
	if x != nil {
		return x.BestHand
	}
	return nil
}

func (x *EvaluateHandResponse) GetHandName() string {
	if x != nil {
		return x.HandName
	}
	return ""
}

type CompareHandsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Player1Hole    []string               `protobuf:"bytes,1,rep,name=player1_hole,json=player1Hole,proto3" json:"player1_hole,omitempty"`          // 2 cards
	Player2Hole    []string               `protobuf:"bytes,2,rep,name=player2_hole,json=player2Hole,proto3" json:"player2_hole,omitempty"`          // 2 cards
	CommunityCards []string               `protobuf:"bytes,3,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"` // 5 cards
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompareHandsRequest) Reset() {
	*x = CompareHandsRequest{}
	mi := &file_proto_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsRequest) ProtoMessage() {}

func (x *CompareHandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsRequest.ProtoReflect.Descriptor instead.
func (*CompareHandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{2}
}

func (x *CompareHandsRequest) GetPlayer1Hole() []string {
	if x != nil {
		return x.Player1Hole
	}
	return nil
}

func (x *CompareHandsRequest) GetPlayer2Hole() []string {
	if x != nil {
		return x.Player2Hole
	}
	return nil
}

func (x *CompareHandsRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

type CompareHandsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Player1BestHand []string               `protobuf:"bytes,1,rep,name=player1_best_hand,json=player1BestHand,proto3" json:"player1_best_hand,omitempty"` // 5 cards
	Player1HandName string                 `protobuf:"bytes,2,opt,name=player1_hand_name,json=player1HandName,proto3" json:"player1_hand_name,omitempty"`
	Player2BestHand []string               `protobuf:"bytes,3,rep,name=player2_best_hand,json=player2BestHand,proto3" json:"player2_best_hand,omitempty"` // 5 cards
	Player2HandName string                 `protobuf:"bytes,4,opt,name=player2_hand_name,json=player2HandName,proto3" json:"player2_hand_name,omitempty"`
	// "Player 1", "Player 2", or "Tie"
	Winner        string `protobuf:"bytes,5,opt,name=winner,proto3" json:"winner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareHandsResponse) Reset() {
	*x = CompareHandsResponse{}
	mi := &file_proto_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareHandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareHandsResponse) ProtoMessage() {}

func (x *CompareHandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareHandsResponse.ProtoReflect.Descriptor instead.
func (*CompareHandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{3}
}

func (x *CompareHandsResponse) GetPlayer1BestHand() []string {
	if x != nil {
		return x.Player1BestHand
	}
	return nil
}

func (x *CompareHandsResponse) GetPlayer1HandName() string {
	if x != nil {
		return x.Player1HandName
	}
	return ""
}

func (x *CompareHandsResponse) GetPlayer2BestHand() []string {
	if x != nil {
		return x.Player2BestHand
	}
	return nil
}

func (x *CompareHandsResponse) GetPlayer2HandName() string {
	if x != nil {
		return x.Player2HandName
	}
	return ""
}

func (x *CompareHandsResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type MonteCarloRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HoleCards      []string               `protobuf:"bytes,1,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`                // exactly 2
	CommunityCards []string               `protobuf:"bytes,2,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"` // 0, 3, 4, or 5 cards (pre-flop, flop, turn, river)
	NumPlayers     int32                  `protobuf:"varint,3,opt,name=num_players,json=numPlayers,proto3" json:"num_players,omitempty"`            // total number of players at the table (2–9)
	Simulations    int32                  `protobuf:"varint,4,opt,name=simulations,proto3" json:"simulations,omitempty"`                            // number of Monte Carlo iterations
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonteCarloRequest) Reset() {
	*x = MonteCarloRequest{}
	mi := &file_proto_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonteCarloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonteCarloRequest) ProtoMessage() {}

func (x *MonteCarloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonteCarloRequest.ProtoReflect.Descriptor instead.
func (*MonteCarloRequest) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{4}
}

func (x *MonteCarloRequest) GetHoleCards() []string {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *MonteCarloRequest) GetCommunityCards() []string {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *MonteCarloRequest) GetNumPlayers() int32 {
	if x != nil {
		return x.NumPlayers
	}
	return 0
}

func (x *MonteCarloRequest) GetSimulations() int32 {
	if x != nil {
		return x.Simulations
	}
	return 0
}

type MonteCarloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Win probability in the range [0, 1].
	WinProbability float64 `protobuf:"fixed64,1,opt,name=win_probability,json=winProbability,proto3" json:"win_probability,omitempty"`
	// Number of simulations that were actually run (may be capped).
	SimulationsRun int32 `protobuf:"varint,2,opt,name=simulations_run,json=simulationsRun,proto3" json:"simulations_run,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonteCarloResponse) Reset() {
	*x = MonteCarloResponse{}
	mi := &file_proto_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonteCarloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonteCarloResponse) ProtoMessage() {}

func (x *MonteCarloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonteCarloResponse.ProtoReflect.Descriptor instead.
func (*MonteCarloResponse) Descriptor() ([]byte, []int) {
	return file_proto_poker_proto_rawDescGZIP(), []int{5}
}

func (x *MonteCarloResponse) GetWinProbability() float64 {
	if x != nil {
		return x.WinProbability
	}
	return 0
}

func (x *MonteCarloResponse) GetSimulationsRun() int32 {
	if x != nil {
		return x.SimulationsRun
	}
	return 0
}

var File_proto_poker_proto protoreflect.FileDescriptor

const file_proto_poker_proto_rawDesc = "" +
	"\n" +
	"\x11proto/poker.proto\x12\x05poker\"]\n" +
	"\x13EvaluateHandRequest\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x01 \x03(\tR\tholeCards\x12'\n" +
	"\x0fcommunity_cards\x18\x02 \x03(\tR\x0ecommunityCards\"P\n" +
	"\x14EvaluateHandResponse\x12\x1b\n" +
	"\tbest_hand\x18\x01 \x03(\tR\bbestHand\x12\x1b\n" +
	"\thand_name\x18\x02 \x01(\tR\bhandName\"\x84\x01\n" +
	"\x13CompareHandsRequest\x12!\n" +
	"\fplayer1_hole\x18\x01 \x03(\tR\vplayer1Hole\x12!\n" +
	"\fplayer2_hole\x18\x02 \x03(\tR\vplayer2Hole\x12'\n" +
	"\x0fcommunity_cards\x18\x03 \x03(\tR\x0ecommunityCards\"\xde\x01\n" +
	"\x14CompareHandsResponse\x12*\n" +
	"\x11player1_best_hand\x18\x01 \x03(\tR\x0fplayer1BestHand\x12*\n" +
	"\x11player1_hand_name\x18\x02 \x01(\tR\x0fplayer1HandName\x12*\n" +
	"\x11player2_best_hand\x18\x03 \x03(\tR\x0fplayer2BestHand\x12*\n" +
	"\x11player2_hand_name\x18\x04 \x01(\tR\x0fplayer2HandName\x12\x16\n" +
	"\x06winner\x18\x05 \x01(\tR\x06winner\"\x9e\x01\n" +
	"\x11MonteCarloRequest\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x01 \x03(\tR\tholeCards\x12'\n" +
	"\x0fcommunity_cards\x18\x02 \x03(\tR\x0ecommunityCards\x12\x1f\n" +
	"\vnum_players\x18\x03 \x01(\x05R\n" +
	"numPlayers\x12 \n" +
	"\vsimulations\x18\x04 \x01(\x05R\vsimulations\"f\n" +
	"\x12MonteCarloResponse\x12'\n" +
	"\x0fwin_probability\x18\x01 \x01(\x01R\x0ewinProbability\x12'\n" +
	"\x0fsimulations_run\x18\x02 \x01(\x05R\x0esimulationsRun2\xec\x01\n" +
	"\x0ePokerEvaluator\x12G\n" +
	"\fEvaluateHand\x12\x1a.poker.EvaluateHandRequest\x1a\x1b.poker.EvaluateHandResponse\x12G\n" +
	"\fCompareHands\x12\x1a.poker.CompareHandsRequest\x1a\x1b.poker.CompareHandsResponse\x12H\n" +
	"\x11MonteCarloWinProb\x12\x18.poker.MonteCarloRequest\x1a\x19.poker.MonteCarloResponseB\x0eZ\ftexsas/protob\x06proto3"

var (
	file_proto_poker_proto_rawDescOnce sync.Once
	file_proto_poker_proto_rawDescData []byte
)

func file_proto_poker_proto_rawDescGZIP() []byte {
	file_proto_poker_proto_rawDescOnce.Do(func() {
		file_proto_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_poker_proto_rawDesc), len(file_proto_poker_proto_rawDesc)))
	})
	return file_proto_poker_proto_rawDescData
}

var file_proto_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_poker_proto_goTypes = []any{
	(*EvaluateHandRequest)(nil),  // 0: poker.EvaluateHandRequest
	(*EvaluateHandResponse)(nil), // 1: poker.EvaluateHandResponse
	(*CompareHandsRequest)(nil),  // 2: poker.CompareHandsRequest
	(*CompareHandsResponse)(nil), // 3: poker.CompareHandsResponse
	(*MonteCarloRequest)(nil),    // 4: poker.MonteCarloRequest
	(*MonteCarloResponse)(nil),   // 5: poker.MonteCarloResponse
}
var file_proto_poker_proto_depIdxs = []int32{
	0, // 0: poker.PokerEvaluator.EvaluateHand:input_type -> poker.EvaluateHandRequest
	2, // 1: poker.PokerEvaluator.CompareHands:input_type -> poker.CompareHandsRequest
	4, // 2: poker.PokerEvaluator.MonteCarloWinProb:input_type -> poker.MonteCarloRequest
	1, // 3: poker.PokerEvaluator.EvaluateHand:output_type -> poker.EvaluateHandResponse
	3, // 4: poker.PokerEvaluator.CompareHands:output_type -> poker.CompareHandsResponse
	5, // 5: poker.PokerEvaluator.MonteCarloWinProb:output_type -> poker.MonteCarloResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_poker_proto_init() }
func file_proto_poker_proto_init() {
	if File_proto_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_poker_proto_rawDesc), len(file_proto_poker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_poker_proto_goTypes,
		DependencyIndexes: file_proto_poker_proto_depIdxs,
		MessageInfos:      file_proto_poker_proto_msgTypes,
	}.Build()
	File_proto_poker_proto = out.File
	file_proto_poker_proto_goTypes = nil
	file_proto_poker_proto_depIdxs = nil
}
